# Site settings
title: "ESU2016 Leipzig: Deeper Mapping"
email: djwrisley@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://esu2016mapping.github.io" # the base hostname & protocol for your site

twitter_username: esu2016Mapping
github_username:  esu2016Mapping

permalink:          pretty
permalink:          /:year/:month-:day.html

# Build settings
markdown: kramdown
